// mobile/src/components/CameraGrid.tsx
import { useVideoPlayer, VideoView } from 'expo-video'
import React, { useEffect, useState } from 'react'
import { Pressable, StyleSheet, Text, View } from 'react-native'
import type { Camera } from '../types'
import { colors, weight } from '../theme'
import { Icon } from './ui'

function CameraTile({ cam, manage, onEdit, onRemove }: {
  cam: Camera
  manage?: boolean
  onEdit?: (c: Camera) => void
  onRemove?: (c: Camera) => void
}) {
  const player = useVideoPlayer(cam.active && cam.streamUrl ? cam.streamUrl : null, (p) => {
    p.loop = true
    p.muted = true
    p.play()
  })

  const [clock, setClock] = useState('')
  useEffect(() => {
    const fmt = () =>
      setClock(new Date().toLocaleString('es-CO', {
        day: '2-digit', month: '2-digit', year: 'numeric',
        hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false,
      }))
    fmt()
    const t = setInterval(fmt, 1000)
    return () => clearInterval(t)
  }, [])

  return (
    <View style={s.tile}>
      {cam.active && cam.streamUrl ? (
        <VideoView player={player} style={s.video} contentFit="cover" nativeControls={false} />
      ) : (
        <View style={s.offline}>
          <Icon name="video-off-outline" size={26} color="#52525B" />
          <Text style={s.offlineText}>Sin señal</Text>
        </View>
      )}

      {cam.active && (
        <View style={s.overlay} pointerEvents="none">
          <View style={s.overlayTop}>
            <View style={s.rec}>
              <View style={s.recDot} />
              <Text style={s.recText}>REC</Text>
            </View>
            <Text style={s.clock}>{clock}</Text>
          </View>
          <View>
            <Text style={s.name}>{cam.name}</Text>
            <Text style={s.location}>{cam.location}</Text>
          </View>
        </View>
      )}

      {manage && (
        <View style={s.actions}>
          <Pressable style={s.action} onPress={() => onEdit?.(cam)}>
            <Icon name="pencil-outline" size={14} color={colors.text} />
          </Pressable>
          <Pressable style={s.action} onPress={() => onRemove?.(cam)}>
            <Icon name="delete-outline" size={14} color={colors.error} />
          </Pressable>
        </View>
      )}
    </View>
  )
}

export function CameraGrid({ cameras, manage, onEdit, onRemove }: {
  cameras: Camera[]
  manage?: boolean
  onEdit?: (c: Camera) => void
  onRemove?: (c: Camera) => void
}) {
  return (
    <View style={s.grid}>
      {cameras.map((c) => (
        <CameraTile key={c.id} cam={c} manage={manage} onEdit={onEdit} onRemove={onRemove} />
      ))}
    </View>
  )
}

const s = StyleSheet.create({
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  tile: {
    width: '48%', aspectRatio: 16 / 10,
    borderRadius: 16, overflow: 'hidden',
    backgroundColor: '#0A0A0F', flexGrow: 1,
  },
  video: { width: '100%', height: '100%' },
  offline: {
    flex: 1, alignItems: 'center', justifyContent: 'center', gap: 6,
    backgroundColor: '#111114',
  },
  offlineText: { fontSize: 12, ...weight.semibold, color: '#52525B' },

  overlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    padding: 9,
    justifyContent: 'space-between',
  },
  overlayTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  rec: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  recDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#EF4444' },
  recText: { fontSize: 9, ...weight.extrabold, letterSpacing: 1, color: '#fff' },
  clock: { fontSize: 8.5, ...weight.semibold, color: 'rgba(255,255,255,0.85)' },

  name: { fontSize: 13, ...weight.extrabold, color: '#fff' },
  location: { ...weight.regular, fontSize: 12, color: 'rgba(255,255,255,0.7)' },

  actions: { position: 'absolute', top: 8, right: 8, flexDirection: 'row', gap: 6 },
  action: {
    width: 26, height: 26, borderRadius: 13,
    backgroundColor: 'rgba(255,255,255,0.92)',
    alignItems: 'center', justifyContent: 'center',
  },
})

// src/components/shared/CameraGrid.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import type { Camera } from '@/types'

defineProps<{
  cameras: Camera[]
  manage?: boolean
}>()

const emit = defineEmits<{
  edit: [camera: Camera]
  remove: [camera: Camera]
}>()

const expanded = ref<string | null>(null)

// Reloj del overlay tipo CCTV
const now = ref(new Date())
let timer: ReturnType<typeof setInterval>
onMounted(() => {
  timer = setInterval(() => (now.value = new Date()), 1000)
})
onUnmounted(() => clearInterval(timer))

function fmtClock(d: Date) {
  return d.toLocaleString('es-CO', {
    day: '2-digit', month: '2-digit', year: 'numeric',
    hour: '2-digit', minute: '2-digit', second: '2-digit',
    hour12: false,
  })
}
</script>

<template>
  <div class="cam-grid">
    <div
      v-for="(cam, i) in cameras"
      :key="cam.id"
      class="cam-tile"
      :class="{ 'cam-tile--expanded': expanded === cam.id, 'cam-tile--off': !cam.active }"
      :style="{ animationDelay: `${i * 60}ms` }"
      @click="expanded = expanded === cam.id ? null : cam.id"
    >
      <div class="cam-video-wrap">
        <video
          v-if="cam.active"
          :src="cam.streamUrl"
          autoplay
          muted
          loop
          playsinline
          class="cam-video"
        />
        <div v-else class="cam-offline">
          <VIcon icon="mdi-video-off-outline" size="28" />
          <span>Sin señal</span>
        </div>

        <!-- Overlay CCTV -->
        <div v-if="cam.active" class="cam-overlay">
          <div class="cam-overlay-top">
            <span class="cam-rec"><span class="cam-rec-dot" /> REC</span>
            <span class="cam-clock">{{ fmtClock(now) }}</span>
          </div>
          <div class="cam-overlay-bottom">
            <span class="cam-name">{{ cam.name }}</span>
            <span class="cam-location">{{ cam.location }}</span>
          </div>
        </div>

        <!-- Acciones admin -->
        <div v-if="manage" class="cam-actions" @click.stop>
          <button class="cam-action" @click="emit('edit', cam)">
            <VIcon icon="mdi-pencil-outline" size="15" />
          </button>
          <button class="cam-action cam-action--danger" @click="emit('remove', cam)">
            <VIcon icon="mdi-delete-outline" size="15" />
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.cam-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 10px;
}

.cam-tile {
  border-radius: 16px;
  overflow: hidden;
  cursor: pointer;
  background: #0A0A0F;
  box-shadow: var(--shadow-sm);
  transition: all 0.25s ease;
  animation: cam-in 0.4s ease both;
}

@keyframes cam-in {
  from { opacity: 0; transform: scale(0.96); }
  to { opacity: 1; transform: scale(1); }
}

.cam-tile--expanded { grid-column: span 2; }
.cam-tile--off { opacity: 0.8; }

.cam-video-wrap { position: relative; aspect-ratio: 16/10; }
.cam-tile--expanded .cam-video-wrap { aspect-ratio: 16/9; }

.cam-video {
  width: 100%; height: 100%;
  object-fit: cover;
  display: block;
  filter: saturate(0.85) contrast(1.05);
}

.cam-offline {
  width: 100%; height: 100%;
  display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 6px;
  color: #52525B; font-size: 11px; font-weight: 600;
  background: repeating-linear-gradient(45deg, #111114, #111114 8px, #16161A 8px, #16161A 16px);
}

.cam-overlay {
  position: absolute; inset: 0;
  display: flex; flex-direction: column; justify-content: space-between;
  padding: 8px 10px;
  background: linear-gradient(rgba(0,0,0,0.35), transparent 30%, transparent 65%, rgba(0,0,0,0.55));
  pointer-events: none;
}

.cam-overlay-top { display: flex; justify-content: space-between; align-items: center; }

.cam-rec {
  display: inline-flex; align-items: center; gap: 4px;
  font-size: 9px; font-weight: 800; letter-spacing: 1px;
  color: white;
}
.cam-rec-dot {
  width: 6px; height: 6px; border-radius: 50%;
  background: #EF4444;
  animation: rec-blink 1.4s ease infinite;
}
@keyframes rec-blink { 0%, 100% { opacity: 1; } 50% { opacity: 0.2; } }

.cam-clock {
  font-size: 8.5px; font-weight: 600;
  color: rgba(255,255,255,0.85);
  font-variant-numeric: tabular-nums;
  font-family: 'Courier New', monospace;
}

.cam-overlay-bottom { display: flex; flex-direction: column; }
.cam-name { font-size: 12px; font-weight: 800; color: white; letter-spacing: -0.2px; }
.cam-location { font-size: 10px; color: rgba(255,255,255,0.7); }

.cam-actions {
  position: absolute; top: 8px; right: 8px;
  display: flex; gap: 6px;
}
.cam-action {
  width: 28px; height: 28px; border: none; border-radius: 50%;
  background: rgba(255,255,255,0.92); color: var(--color-text-primary);
  cursor: pointer; display: flex; align-items: center; justify-content: center;
  transition: transform 0.12s ease;
}
.cam-action:active { transform: scale(0.88); }
.cam-action--danger { color: var(--color-error); }
</style>
